apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dou1cm4ag-nodejs 
  janus-idp.io/tekton: dou1cm4ag-nodejs
  backstage.io/kubernetes-id: dou1cm4ag-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dou1cm4ag-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  