apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dou1cm4ag-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dou1cm4ag-nodejs 
  name: dou1cm4ag-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: dou1cm4ag-nodejs 
